apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: api-gateway
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: api-gateway
data:
  KONG_DATABASE: postgres
  KONG_PG_HOST: postgresql.api-gateway.svc.cluster.local
  KONG_PG_PORT: "5432"
  KONG_PG_DATABASE: kong
  KONG_PG_USER: kong
  KONG_PG_SSL: "on"
  KONG_PG_SSL_VERIFY: "on"
  KONG_PROXY_LISTEN: "0.0.0.0:8000 reuseport backlog=16384, 0.0.0.0:8443 http2 ssl reuseport backlog=16384"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001"
  KONG_STATUS_LISTEN: "0.0.0.0:8100"
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_PROXY_ACCESS_LOG: /dev/stdout
  KONG_PROXY_ERROR_LOG: /dev/stderr
  KONG_LOG_LEVEL: notice
  KONG_PLUGINS: bundled,rate-limiting,cors,jwt,key-auth,prometheus,ip-restriction,subscription-validator,ai-gateway
  KONG_NGINX_WORKER_PROCESSES: "auto"
  KONG_UPSTREAM_KEEPALIVE_POOL_SIZE: "256"
  KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS: "10000"
  KONG_UPSTREAM_KEEPALIVE_IDLE_TIMEOUT: "60"
  KONG_PREFIX: /kong_prefix
  KONG_HEADERS: "off"
  KONG_TRUSTED_IPS: "0.0.0.0/0,::/0"
  KONG_REAL_IP_HEADER: X-Forwarded-For
  KONG_REAL_IP_RECURSIVE: "on"
  KONG_SSL_PROTOCOLS: "TLSv1.2 TLSv1.3"
  KONG_SSL_PREFER_SERVER_CIPHERS: "on"
